name: build-test-tag

on:
  push:
    branches:
      - main

env:
  go-version: 1.17

jobs:
  build_test_tag:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ env.go-version }}

    - name: Build
      run: go build -v ./...

    - name: Test
      run: sudo go test -v -cover ./...
    
    - name: Bump version and push tag
      uses: hennejg/github-tag-action@v4.1.jh1
      with:
        release_branches: main
        github_token: ${{ secrets.GITHUB_TOKEN }}
