name: build-test

on:
  push:
    branches:
      - "*"

env:
  go-version: 1.17

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ env.go-version }}

    - name: Build
      run: go build -v ./...

    - name: Test
      run: sudo go test -v -cover ./...
