name: ci

on:
  push:
    branches: "*"

env:
  go-version: 1.17

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ env.go-version }}

    - name: Build
      run: go build -v ./...

    - name: Test
      run: sudo go test -v -cover ./...

  release:
    runs-on: ubuntu-latest
    needs: [build_and_test]
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ env.go-version }}

      - name: build and package
        run: bash ./package_release.sh

      - name: set release vars
        id: release-vars
        run: echo ::set-output name=short_ref::${GITHUB_REF#refs/*/}

      - uses: "marvinpinto/action-automatic-releases@v1.2.1"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: ${{ steps.release-vars.outputs.short_ref }}
          prerelease: true
          title: ${{ steps.release-vars.outputs.short_ref }}
          files: |
            LICENSE
            ./artifacts/*.zip
            ./artifacts/*.tar.gz
