name: release

on:
  push:
    branches:
      - main

env:
  go-version: 1.17

jobs:
  build_test_tag:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: '0'

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ env.go-version }}

    - name: Build
      run: go build -v ./...

    - name: Test
      run: sudo go test -v -cover ./...
    
    - id: bump
      name: Bump version and push tag
      uses: anothrNick/github-tag-action@1.36.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        WITH_V: true
        RELEASE_BRANCHES: main
        
    - name: build and package
      run: bash ./package_release.sh

    - uses: "marvinpinto/action-automatic-releases@v1.2.1"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        prerelease: false
        title: ${{ steps.bump.outputs.new_tag }}
        automatic_release_tag: ${{ steps.bump.outputs.new_tag }}
        files: |
          LICENSE
          ./artifacts/*.zip
          ./artifacts/*.tar.gz

