name: sem-ver-test

on:
  pull_request:
    branches:
    - auto-sem-ver
    types:
    - closed

env:
  go-version: 1.17

jobs:
  build_test_tag:
    if: github.event.pull_request.merged == 'true'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - id: bump
      uses: zwaldowski/match-label-action@v2
      with:
        allowed: major, minor, patch

    - run: echo ${{ steps.bump.outputs.match }}
